// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GP_GAMEPACKET_H_
#define FLATBUFFERS_GENERATED_GP_GAMEPACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 3,
             "Non-compatible flatbuffers version included");

namespace GamePacket {

struct CardData;

struct Message;
struct MessageBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) CardData FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t rank_;
  int16_t suit_;

 public:
  CardData()
      : rank_(0),
        suit_(0) {
  }
  CardData(int16_t _rank, int16_t _suit)
      : rank_(::flatbuffers::EndianScalar(_rank)),
        suit_(::flatbuffers::EndianScalar(_suit)) {
  }
  int16_t rank() const {
    return ::flatbuffers::EndianScalar(rank_);
  }
  int16_t suit() const {
    return ::flatbuffers::EndianScalar(suit_);
  }
};
FLATBUFFERS_STRUCT_END(CardData, 4);

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_CARD = 6,
    VT_FUNC = 8
  };
  const ::flatbuffers::String *data() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATA);
  }
  const GamePacket::CardData *card() const {
    return GetStruct<const GamePacket::CardData *>(VT_CARD);
  }
  const ::flatbuffers::String *func() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FUNC);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyString(data()) &&
           VerifyField<GamePacket::CardData>(verifier, VT_CARD, 2) &&
           VerifyOffset(verifier, VT_FUNC) &&
           verifier.VerifyString(func()) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::String> data) {
    fbb_.AddOffset(Message::VT_DATA, data);
  }
  void add_card(const GamePacket::CardData *card) {
    fbb_.AddStruct(Message::VT_CARD, card);
  }
  void add_func(::flatbuffers::Offset<::flatbuffers::String> func) {
    fbb_.AddOffset(Message::VT_FUNC, func);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> data = 0,
    const GamePacket::CardData *card = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> func = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_func(func);
  builder_.add_card(card);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message> CreateMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *data = nullptr,
    const GamePacket::CardData *card = nullptr,
    const char *func = nullptr) {
  auto data__ = data ? _fbb.CreateString(data) : 0;
  auto func__ = func ? _fbb.CreateString(func) : 0;
  return GamePacket::CreateMessage(
      _fbb,
      data__,
      card,
      func__);
}

inline const GamePacket::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<GamePacket::Message>(buf);
}

inline const GamePacket::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GamePacket::Message>(buf);
}

inline bool VerifyMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GamePacket::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GamePacket::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GamePacket::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GamePacket::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace GamePacket

#endif  // FLATBUFFERS_GENERATED_GP_GAMEPACKET_H_
